table 'Job User Tag'
	lineageTag: a9ac1f29-0185-4949-9b4f-83e4f58c3585

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: a0b41278-d3c1-45d0-9f10-d2c95798b5c9
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = Automatic

	column tag
		dataType: string
		lineageTag: d7e3ee69-4128-4fd1-8cb6-183d51ddec50
		summarizeBy: none
		sourceColumn: tag

		annotation SummarizationSetBy = Automatic

	partition 'Job User Tag' = m
		mode: import
		queryGroup: References
		source =
				let
				    Source = Csv.Document(Web.Contents("https://drive.usercontent.google.com/u/0/uc?id=1lToaUKh6PADJ539r_Aj0UfHL4dMx16S9&export=download"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_position_id", Int64.Type}, {"tag", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

