table 'Job Assigned To Bridge'
	lineageTag: a23d70a0-906b-45e9-b6eb-f2e54271fa06

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: 463caa23-24d1-47fd-912a-296ce006ea7f
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = User

	column assigned_to
		dataType: string
		lineageTag: 0e8d189c-a555-4dd1-ab30-166d7a262be4
		summarizeBy: none
		sourceColumn: assigned_to

		annotation SummarizationSetBy = Automatic

	partition 'Job Assigned To Bridge' = m
		mode: import
		queryGroup: References
		source =
				let
				    Source = Csv.Document(Web.Contents("https://drive.usercontent.google.com/u/0/uc?id=1baDLWADEEDefnFr7h3pz-hWds_3i82KX&export=download"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Source", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_position_id", Int64.Type}, {"assigned_to", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

