table Reference
	lineageTag: b885eee8-b7ee-4f2f-9ec6-ed55be4ca767

	measure 'Avg Requested To Reviewed Time' = AVERAGE(Reference[requested_to_reviewed_time])
		displayFolder: _Avg Time
		lineageTag: 041a0674-71e9-4b34-9cad-d74563756b46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Requested To Submitted Time' = AVERAGE(Reference[requested_to_completed_time])
		displayFolder: _Avg Time
		lineageTag: 66928b21-7fd6-46c2-9aad-085899a5ff6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Submitted To Reviewed Time' = AVERAGE(Reference[completed_to_reviewed_time])
		displayFolder: _Avg Time
		lineageTag: 385f93cf-9173-4941-862c-8656e5462482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Approved References' = ```
			
			CALCULATE([Number of References],
			    Reference[ref_approval_status] = "Approved",
			    USERELATIONSHIP(
			        Reference[ref_approved_date], 
			        Dates[Date]
			    )
			)
			```
		formatString: 0
		displayFolder: _References
		lineageTag: 1669d29c-abae-4076-8450-325285ca51c5

	measure 'Number of Submitted References' =
			
			CALCULATE(
			    COUNT(Reference[requested_to_completed_time]),
			    USERELATIONSHIP(
			        Reference[ref_completed_date],
			        Dates[Date]
			    )
			)
		formatString: # ##0
		displayFolder: _References
		lineageTag: 571e7b98-73cc-4750-8f12-2cb3d219067f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Number of Months for Rolling Avg' = COALESCE(SELECTEDVALUE('Rolling Months'[Rolling Months]), 3)
		formatString: 0
		displayFolder: _Utility
		lineageTag: 7265594d-34ca-4b81-8e8e-a893d41f95d1

	measure 'Number of References' = COUNTROWS(Reference) + 0
		formatString: # ##0
		displayFolder: _References
		lineageTag: fe038b7a-df2e-4144-9133-1f64b61e0628

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Rolling Avg Requested to Submitted Days' = ```
			
			CALCULATE (
			    [Avg Requested to Submitted Days],
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    ),
			    USERELATIONSHIP(
			        Reference[ref_completed_date], 
			        Dates[Date]
			    )
			)
			```
		displayFolder: _Rolling Avg Days
		lineageTag: 7782a940-1041-4e40-aec4-6602b6abdc92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Requested to Reviewed Days' = ```
			
			CALCULATE (
			    [Avg Requested to Reviewed Days],
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    ),
			    USERELATIONSHIP(
			        Reference[ref_approved_date], 
			        Dates[Date]
			    )
			)
			```
		displayFolder: _Rolling Avg Days
		lineageTag: 05c43ece-3a31-45a5-b65d-28685ca8eab2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Requested to Reviewed Days' = DIVIDE([Avg Requested To Reviewed Time], (60*60*24))
		displayFolder: _Avg Days
		lineageTag: 0b1c66ca-7c42-4173-ac1b-33d9d5f49b32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Requested to Submitted Days' = DIVIDE([Avg Requested To Submitted Time], (60*60*24))
		displayFolder: _Avg Days
		lineageTag: 5a3f2847-3c4a-4544-8c20-ce3dc83b2edc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Submitted to Reviewed Days' = DIVIDE([Avg Submitted To Reviewed Time], (60*60*24))
		displayFolder: _Avg Days
		lineageTag: ef0454e8-fda6-420a-b489-99a7f8ca969c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Number of Declined References' = ```
			
			CALCULATE([Number of References],
			    Reference[ref_approval_status] = "Declined",
			    USERELATIONSHIP(
			        Reference[ref_approved_date], 
			        Dates[Date]
			    )
			)
			```
		formatString: 0
		displayFolder: _References
		lineageTag: b09ce729-9450-46c9-b8b4-30e300fb6ed5

	measure 'Number of Reviewed References' = [Number of Approved References] + [Number of Declined References]
		formatString: 0
		displayFolder: _References
		lineageTag: e575a2fc-989c-417f-8ebb-1f2cdd7a0084

	measure 'Approval Rate' = DIVIDE([Number of Approved References], [Number of References])
		formatString: 0%;-0%;0%
		displayFolder: _References
		lineageTag: 28c48381-621b-443f-997e-fa8941e5f8d3

	measure 'Been Reviewed %' = DIVIDE([Number of Reviewed References], [Number of References])
		displayFolder: _References
		lineageTag: 81beebc8-283f-4158-96dd-63eae68f9550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Been Submitted %' = DIVIDE([Number of Submitted References], [Number of References])
		displayFolder: _References
		lineageTag: d362ea6f-5537-4c8b-bdf0-e7db7eb936a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rolling Avg Submitted to Reviewed Days' = ```
			
			CALCULATE (
			    [Avg Submitted to Reviewed Days],
			    DATESINPERIOD (
			        Dates[Date],
			        LASTDATE (Dates[Date]),
			        -[Number of Months for Rolling Avg],
			        MONTH
			    ),
			    USERELATIONSHIP(
			        Reference[ref_approved_date], 
			        Dates[Date]
			    )
			)
			```
		displayFolder: _Rolling Avg Days
		lineageTag: 0efb6bc3-ebd4-4426-a7dc-6946c495c498

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column completed_to_reviewed_days
		dataType: int64
		lineageTag: 23629e9c-98e8-470a-b6a3-04d973f3462c
		summarizeBy: none
		sourceColumn: completed_to_reviewed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column completed_to_reviewed_time
		dataType: double
		lineageTag: 0e6cfed2-2615-438d-af84-6853ec889c5f
		summarizeBy: sum
		sourceColumn: completed_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cr_created_at
		dataType: dateTime
		formatString: Long Time
		lineageTag: fd8ae5a7-4295-4dd8-9852-84ddfb7abde8
		summarizeBy: none
		sourceColumn: cr_created_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column job_position_id
		dataType: int64
		formatString: 0
		lineageTag: 499c4c8c-744c-4b9e-91a0-f720075f052c
		summarizeBy: none
		sourceColumn: job_position_id

		annotation SummarizationSetBy = Automatic

	column marked_compliant_at
		dataType: dateTime
		formatString: Long Time
		lineageTag: a3f7d584-2d3c-4e2a-916e-34adf2da4340
		summarizeBy: none
		sourceColumn: marked_compliant_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ref_approval_status
		dataType: string
		lineageTag: 8d140338-c260-4689-9f92-89a606f666b5
		summarizeBy: none
		sourceColumn: ref_approval_status

		annotation SummarizationSetBy = Automatic

	column ref_approved_at
		dataType: dateTime
		formatString: Long Time
		lineageTag: 7ff57eb8-6ca7-45bc-8b04-619c291f01da
		summarizeBy: none
		sourceColumn: ref_approved_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ref_approved_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76e1ce4e-a2eb-41ef-9759-f80f2c52078d
		summarizeBy: none
		sourceColumn: ref_approved_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_completed_at
		dataType: dateTime
		formatString: Long Time
		lineageTag: d8c991f5-3ad3-49b5-bc02-afffa731d9c2
		summarizeBy: none
		sourceColumn: ref_completed_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ref_completed_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3416eb6a-af72-4a4e-bbca-e8c90d25fd42
		summarizeBy: none
		sourceColumn: ref_completed_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_requested_at
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5a78b2db-c16f-4097-9d11-45e497daa335
		summarizeBy: none
		sourceColumn: ref_requested_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ref_requested_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f94f6bd6-c89f-4c1e-ab96-c1ca3e7bc6e8
		summarizeBy: none
		sourceColumn: ref_requested_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ref_status
		dataType: string
		lineageTag: b6f45942-620d-438f-be38-a38cb51882ce
		summarizeBy: none
		sourceColumn: ref_status

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_days
		dataType: int64
		lineageTag: 17416bd8-6afd-44af-b464-b18d86d98f13
		summarizeBy: none
		sourceColumn: requested_to_completed_days

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation SummarizationSetBy = User

	column requested_to_completed_time
		dataType: double
		lineageTag: 483615f0-6590-491f-ac76-7bdf4057728f
		summarizeBy: sum
		sourceColumn: requested_to_completed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_compliant_time
		dataType: double
		lineageTag: bcc01aa2-fa25-47b3-b88e-c408aef4b799
		summarizeBy: sum
		sourceColumn: requested_to_compliant_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column requested_to_reviewed_time
		dataType: double
		lineageTag: 3b27de7d-a880-4f41-bc8b-ad7f7f23dd2c
		summarizeBy: sum
		sourceColumn: requested_to_reviewed_time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_mandatory
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a337263-ea0e-42e8-ac94-380320303a74
		summarizeBy: none
		sourceColumn: is_mandatory

		annotation SummarizationSetBy = Automatic

	column ref_package_name
		dataType: string
		lineageTag: f2df5504-f1f0-4fe6-a5fe-b5767d3b808a
		summarizeBy: none
		sourceColumn: ref_package_name

		annotation SummarizationSetBy = Automatic

	column ref_form_name
		dataType: string
		lineageTag: 650694b2-e78a-4195-8b90-28f49af2635b
		summarizeBy: none
		sourceColumn: ref_form_name

		annotation SummarizationSetBy = Automatic

	column cr_created_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 39bf83cf-e547-45eb-9e94-287d105ff578
		summarizeBy: none
		sourceColumn: cr_created_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marked_compliant_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1188985c-76de-4c7f-9ee9-788a700da917
		summarizeBy: none
		sourceColumn: marked_compliant_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column requested_to_reviewed_days
		dataType: int64
		formatString: 0
		lineageTag: 2ffda156-df2a-4906-96bb-10d6f06588ee
		summarizeBy: sum
		sourceColumn: requested_to_reviewed_days

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_days
		dataType: int64
		formatString: 0
		lineageTag: 4332af12-e8d6-498f-8972-fce7e5282055
		summarizeBy: sum
		sourceColumn: requested_to_compliant_days

		annotation SummarizationSetBy = Automatic

	column requested_to_completed_category
		dataType: string
		lineageTag: ae2fa91e-0b27-4351-8b4b-88db04df3a20
		summarizeBy: none
		sourceColumn: requested_to_completed_category

		annotation SummarizationSetBy = Automatic

	column completed_to_reviewed_category
		dataType: string
		lineageTag: baa9961c-0868-4418-8665-8faaabd55300
		summarizeBy: none
		sourceColumn: completed_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_reviewed_category
		dataType: string
		lineageTag: 1e576842-aa2a-4d0e-b7c5-df4dabfa6a25
		summarizeBy: none
		sourceColumn: requested_to_reviewed_category

		annotation SummarizationSetBy = Automatic

	column requested_to_compliant_category
		dataType: string
		lineageTag: 591b705c-da71-476b-8b43-3890c74292f5
		summarizeBy: none
		sourceColumn: requested_to_compliant_category

		annotation SummarizationSetBy = Automatic

	partition Reference = m
		mode: import
		queryGroup: References
		source =
				let
				    Source = Csv.Document(Web.Contents("https://drive.usercontent.google.com/u/0/uc?id=1mQj30vUWHMDdVPJVJk4qLh9jD3BYCvSM&export=download"),[Delimiter=",", Columns=26, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_position_id", Int64.Type}, {"ref_requested_at", type datetime}, {"ref_requested_date", type date}, {"ref_completed_at", type datetime}, {"ref_completed_date", type date}, {"ref_approved_at", type datetime}, {"ref_approved_date", type date}, {"is_mandatory", type logical}, {"ref_package_name", type text}, {"ref_form_name", type text}, {"cr_created_at", type datetime}, {"marked_compliant_at", type datetime}, {"requested_to_completed_time", type number}, {"completed_to_reviewed_time", type number}, {"requested_to_reviewed_time", type number}, {"requested_to_compliant_time", type number}, {"ref_status", type text}, {"ref_approval_status", type text}, {"requested_to_completed_days", Int64.Type}, {"completed_to_reviewed_days", Int64.Type}, {"requested_to_reviewed_days", Int64.Type}, {"requested_to_compliant_days", Int64.Type}, {"requested_to_completed_category", type text}, {"completed_to_reviewed_category", type text}, {"requested_to_reviewed_category", type text}, {"requested_to_compliant_category", type text}}),
				    #"Extracted Time" = Table.TransformColumns(#"Changed Type",{{"ref_completed_at", DateTime.Time, type time}, {"ref_approved_at", DateTime.Time, type time}, {"ref_requested_at", DateTime.Time, type time}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Extracted Time", "cr_created_at", "cr_created_date"),
				    #"Extracted Date" = Table.TransformColumns(#"Duplicated Column",{{"cr_created_date", DateTime.Date, type date}}),
				    #"Extracted Time1" = Table.TransformColumns(#"Extracted Date",{{"cr_created_at", DateTime.Time, type time}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Extracted Time1", "marked_compliant_at", "marked_compliant_date"),
				    #"Extracted Date1" = Table.TransformColumns(#"Duplicated Column1",{{"marked_compliant_date", DateTime.Date, type date}}),
				    #"Extracted Time2" = Table.TransformColumns(#"Extracted Date1",{{"marked_compliant_at", DateTime.Time, type time}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Extracted Time2",{"job_position_id", "ref_requested_at", "ref_requested_date", "ref_completed_at", "ref_completed_date", "ref_approved_at", "ref_approved_date", "is_mandatory", "ref_package_name", "ref_form_name", "cr_created_at", "cr_created_date", "marked_compliant_at", "marked_compliant_date", "requested_to_completed_time", "completed_to_reviewed_time", "requested_to_reviewed_time", "requested_to_compliant_time", "ref_status", "ref_approval_status", "requested_to_completed_days", "completed_to_reviewed_days", "requested_to_reviewed_days", "requested_to_compliant_days", "requested_to_completed_category", "completed_to_reviewed_category", "requested_to_reviewed_category", "requested_to_compliant_category"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

